const ROOT_PRODUCTS = document.getElementById('services')
const ROOT_EXAPLES = document.getElementById('exaples')
const ROOT_ACTION = document.getElementById('action')
const ROOT_HEADER = document.getElementById('header')
const ROOT_MAIN = document.getElementById('main')
